### ISSUE TITLE
“Creation error: geolocation unavailable” when trying to save items

### ISSUE THREAD

**Issue by francescomambrini** [EAGLE-BPN/flagship-mobile-app#7]
Error persists even after activating the geolocation in the Settings

**Comment by francescomambrini** [comment]
The issue was reported to me by a tester. I was unable to replicate the issue

**Comment by MaximilianHeiden** [comment]
Hey, 

I  just  wanted to show you something really  amazing, please  check it out here <http://micaela.spencerbrosoiltankremoval.com/e8fh/88>

Yours truly, mlh.heiden
